#! /usr/bin/env python
# encoding: utf-8

APPNAME = "libbar"
VERSION = "1.0.0"


NO_RECURSE = False


def options(opt):
    opt.load("compiler_cxx")


def configure(conf):
    conf.load("compiler_cxx")


def build(bld):
    bld.stlib(
        features="cxx",
        target="bar",
        use=["baz"],
        source="src/bar/bar.cpp",
        export_includes="src",
    )
