#! /usr/bin/env python
# encoding: utf-8

APPNAME = "libbaz"
VERSION = "1.0.0"


def resolve(ctx):
    pass


def options(opt):
    opt.load("compiler_cxx")


def configure(conf):
    conf.load("compiler_cxx")


def build(bld):
    bld.stlib(
        features="cxx", target="baz", source="src/baz/baz.cpp", export_includes="src"
    )
