#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'libbar'
VERSION = '1.0.0'

def resolve(ctx):
    pass

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')

def build(bld):
    bld.shlib(features='cxx',
              target='bar',
              source='src/foo/bar.cpp',
              export_includes='src')
