#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'clang_compilation_database'
VERSION = '0.1.0'


def options(opt):
    opt.load('compiler_cxx')


def configure(conf):
    conf.load('c compiler_cxx clang_compilation_database')


def build(bld):

    bld.program(
        features='cxxprogram',
        source='main.cpp',
        target='clang_compilation_database')
