#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'test_add_dependency'
VERSION = '1.0.0'

import mock
import os

def resolve(ctx):

    def mock_resolve(ctx, path):
        """ Mocking the resolve function which is the one called when
        fetching a dependency"""
        p = os.path.join(path, 'test-dependency')
        os.makedirs(p)
        return p

    resolver = mock.Mock()
    resolver.resolve.side_effect = mock_resolve
    resolver.hash.return_value = 'h4sh'

    ctx.add_dependency('test-dependency', resolver, recurse=False)

    def libfoo_resolve(ctx, path):
        """ Mocking the resolve function which is the one called when
        fetching a dependency"""
        p = os.path.join(path, 'libfoo')

        return p

    foo_resolver = mock.Mock()
    foo_resolver.resolve.side_effect = libfoo_resolve
    foo_resolver.hash.return_value = 'h4sh'

    ctx.add_dependency('libfoo', foo_resolver, optional=False, recurse=True)


def options(opt):
    pass

def configure(conf):
    pass


def build(bld):
    pass
