#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'test_add_dependency'
VERSION = '1.0.0'

import mock
import os

def resolve(ctx):

    resolver = mock.Mock()
    resolver.name = 'test-dependency'

    def mock_resolve(ctx, path):
        """ Mocking the resolve function which is the one called when
        fetching a dependency"""
        p = os.path.join(path, resolver.name)
        os.makedirs(p)
        return p

    resolver.resolve.side_effect=mock_resolve
    resolver.hash.return_value='h4sh'

    ctx.add_dependency('test-dependency', resolver, recurse=False)

    # @todo enable
    #assert ctx.has_dependency_path(resolver.name)

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    pass
