#! /usr/bin/env python
# encoding: utf-8

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='cxx_test'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def options(opt):
    opt.load('cxx_mkspec')

def configure(conf):
    conf.load('cxx_mkspec')

def build(bld):

	bld.program(source='main.cpp', target='app')

