#! /usr/bin/env python
# encoding: utf-8


APPNAME = 'test_create_virtualenv'
VERSION = '1.0.0'


def resolve(ctx):
    ctx.add_dependency(
        name='virtualenv',
        recurse=False,
        optional=False,
        resolver='git',
        method='checkout',
        checkout='15.1.0',
        sources=['github.com/pypa/virtualenv.git'])


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    pass
