#! /usr/bin/env python
# encoding: utf-8
import os

from waflib.extras.wurf.compat import IS_PY2

APPNAME = 'test_create_virtualenv'
VERSION = '1.0.0'


def resolve(ctx):

    ctx.add_dependency(
        name='virtualenv',
        recurse=False,
        optional=False,
        resolver='git',
        method='checkout',
        checkout='15.1.0',
        sources=['github.com/pypa/virtualenv.git'])


def options(opt):
    pass


def configure(conf):

    env = dict(os.environ)

    # Make sure the virtualenv Python module is in path
    env.update({'PYTHONPATH': os.path.pathsep.join(
        [conf.dependency_path('virtualenv')])})

    conf.create_virtualenv(env=env)


def build(bld):
    pass
