#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'test_create_virtualenv'
VERSION = '1.0.0'


def options(opt):
    pass


def configure(conf):
    conf.create_virtualenv()


def build(bld):
    pass
