#! /usr/bin/env python
# encoding: utf-8

from fake_git import FakeGit

APPNAME = "optional_dependencies"
VERSION = "1.0.0"


def resolve(ctx):
    # Get the registry and replace the git builder
    ctx.registry.provide_function("git", FakeGit, override=True)

    # Rebuild the dependency manager
    ctx.dependency_manager = ctx.registry.require("dependency_manager")


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    pass
