#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'test_http_dependency'
VERSION = '1.0.0'

def resolve(ctx):

    ctx.add_dependency(
        name='cxx-prettyprint',
        internal=False,
        optional=False,
        resolver='http',
        method='extract',
        sources=['https://github.com/louisdx/cxx-prettyprint/zipball/master'])

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')

def build(bld):

    # cxx-prettyprint is a header-only library so we just need to
    # export its include
    bld(export_includes=bld.dependency_path('cxx-prettyprint'),
        name='cxx_prettyprint')

    print("WOOOTH {}".format(bld.dependency_path('cxx-prettyprint')))

    bld.program(features='cxx',
                source='main.cpp',
                target='app')
