#! /usr/bin/env python
# encoding: utf-8

import os

APPNAME = "test_http_dependency"
VERSION = "1.0.0"


def resolve(ctx):
    ctx.add_dependency(
        name="endian",
        internal=False,
        optional=False,
        resolver="http",
        extract=True,
        filename="endian-4.0.0.zip",
        source="https://github.com/steinwurf/endian/archive/4.0.0.zip",
    )


def options(opt):
    opt.load("compiler_cxx")


def configure(conf):
    conf.load("compiler_cxx")


def build(bld):
    # endian is a header-only library so we just need to
    # export its include. The zip archive cotains one folder so we
    # need to use that one.

    endian_dirs = os.listdir(bld.dependency_path("endian"))

    if len(endian_dirs) != 1:
        # There should be only one directory
        bld.fatal(f"There should be only one contained dir in the zip {endian_dirs}")

    endian_path = os.path.join(bld.dependency_path("endian"), endian_dirs[0], "src")

    bld(export_includes=endian_path, name="endian")

    bld.program(
        features="cxx",
        source="main.cpp",
        target="app",
        cxxflags="-std=c++11",
        use=["endian"],
    )
