#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'optional_dependencies'
VERSION = '1.0.0'


def resolve(ctx):
    ctx.add_dependency(
        name='foo',
        resolver='git',
        method='checkout',
        internal=True,
        checkout='1.3.3.7',
        sources=['github.com/acme-corp/foo.git'])


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    pass
