#! /usr/bin/env python
# encoding: utf-8

from fake_git import FakeGit

APPNAME = "optional_dependencies"
VERSION = "1.0.0"


def resolve(ctx):

    # Get the registry and replace the git builder
    ctx.registry.provide_function("git", FakeGit, override=True)

    # Rebuild the dependency manager
    ctx.dependency_manager = ctx.registry.require("dependency_manager")

    ctx.add_dependency(
        name="foo",
        resolver="git",
        method="checkout",
        internal=True,
        checkout="1.3.3.7",
        sources=["github.com/acme-corp/foo.git"],
    )


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    pass
