#! /usr/bin/env python
# encoding: utf-8

VERSION = '1.0.0'

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')

def build(bld):
    bld.stlib(features='cxx',
              target='foo',
              source='src/foo/foo.cpp',
              use=['bar'],
              export_includes='src')
