#! /usr/bin/env python
# encoding: utf-8


import sys
from fake_git import FakeGit

APPNAME = "test_add_dependency"
VERSION = "1.0.0"


def resolve(ctx):
    # Get the registry and replace the git builder
    ctx.registry.provide_function("git", FakeGit, override=True)

    # Rebuild the dependency manager
    ctx.dependency_manager = ctx.registry.require("dependency_manager")

    if "--some_option" in sys.argv:
        ctx.enable_dependency("extra")


def options(opt):
    opt.load("compiler_cxx")
    opt.add_option(
        "--some_option",
        default=False,
        action="store_true",
        help="Build with the extra library",
    )


def configure(conf):
    conf.load("compiler_cxx")


def build(bld):
    defines = []
    if bld.options.some_option:
        defines.append("EXTRA")

    bld.program(
        features="cxx",
        source="main.cpp",
        target="app",
        use=["foo", "baz"],
        defines=defines,
    )
