#! /usr/bin/env python
# encoding: utf-8

APPNAME = "test_create_venv"
VERSION = "1.0.0"


def options(opt):

    # Allows us to control the download path of the venv
    opt.add_option("--download_path")


def configure(conf):
    conf.create_venv()


def build(bld):
    venv = bld.create_venv(system_site_packages=True)
    venv.run("python -m pip install pytest")
