#! /usr/bin/env python
# encoding: utf-8

APPNAME = "test_create_venv"
VERSION = "1.0.0"


def configure(conf):
    conf.create_venv()


def build(bld):
    venv = bld.create_venv(cwd=bld.bldnode.abspath())
    venv.run("python -m pip install pytest")
