#! /usr/bin/env python
# encoding: utf-8

from fake_url_download import FakeUrlDownload

APPNAME = "test_post_resolve"
VERSION = "1.0.0"


def resolve(ctx):
    # Get the registry and replace the git builder
    ctx.registry.provide_function("url_download", FakeUrlDownload.build, override=True)

    # Rebuild the dependency manager
    ctx.dependency_manager = ctx.registry.require("dependency_manager")


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    pass
