#! /usr/bin/env python
# encoding: utf-8

APPNAME = "fail_recurse"
VERSION = "1.0.0"


BUILD_RECURSE = True


def resolve(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    pass
