from . import checkoutput

# String used when printing a RunResult
run_string = """RunResult
command:\n{}
path:\n{}
stdout:\n{}
stderr:\n{}
returncode:\n{}
time:\n{}"""

class RunResult:
    """ Stores the results from running a command

    Attributes:

    :command: The command that was executed
    :path: Path where the command was executed
    :stdout: The standard output stream generated by the command
    :stderr: The standard error stream generated by the command
    :returncode: The return code set after invoking the command
    :time: The time it took to execute the command
    """

    def __init__(self, command, path, stdout, stderr, returncode, time):
        """ Create a new RunResult object
        """

        self.command = command
        self.path = path

        # The stdout and stderr are wrapped in a CheckOutput object to make
        # it easy to assert whether it contains specific data / strings.
        self.stdout = checkoutput.CheckOutput(stdout)
        self.stderr = checkoutput.CheckOutput(stderr)
        self.returncode = returncode
        self.time = time

    def __str__(self):
        """ Print the RunResult object as a string
        """
        return run_string.format(self.command, self.path, self.stdout,
                                 self.stderr, self.returncode, self.time)
