#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'libfoo'
VERSION = '1.0.0'

def resolve(ctx):
    pass

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')

def build(bld):
    bld.shlib(features='cxx',
              target='foo',
              source='src/foo/foo.cpp',
              export_includes='src')
