#! /usr/bin/env python
# encoding: utf-8

VERSION = '1.0.0'

def resolve(ctx):
    
    ctx.add_dependency(
        name='bar',
        recurse=True,
        optional=False,
        resolver='git',
        method='checkout',
        checkout='someh4sh',
        sources=['bitbucket.com/acme-corp/bar.git',
                 'gitlab.com/acme-corp/bar.git'])

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')

def build(bld):
    bld.shlib(features='cxx',
              target='foo',
              source='src/foo/foo.cpp',
              use=['bar'],
              export_includes='src')
