#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'waf-tools-tester'
VERSION = '0.1.0'

def build(bld):

    if bld.is_toplevel():

        bld.program(
            features='cxx test',
            source='main.cpp',
            target='waf-tools-tester')
