#! /usr/bin/env python
# encoding: utf-8

# the following two variables are used by the target "waf dist"
VERSION = '0.0.1'
APPNAME = 'cxx_test'

# these variables are mandatory ('/' are converted automatically)
top = '.'


def options(opt):
    opt.load("dependency_bundle")

    import waflib.extras.dependency_bundle as bundle
    import waflib.extras.dependency_resolve as resolve

    bundle.add_dependency(opt, resolve.ResolveGitMajorVersion(
        name='mkspec',
        git_repository='git://github.com/steinwurf/external-waf-mkspec.git',
        major_version=1))
    opt.load('wurf_cxx_mkspec')


def configure(conf):
    #conf.filter_mkspec(lambda mkspec: "default" in mkspec)
    conf.load("dependency_bundle")
    conf.load('wurf_cxx_mkspec')


def build(bld):
    bld.program(source='main.cpp', target='app')
