#! /usr/bin/env python
# encoding: utf-8

from fake_git import FakeGit

APPNAME = "test_add_dependency"
VERSION = "1.0.0"


def resolve(ctx):
    # Get the registry and replace the git builder
    ctx.registry.provide_function("git", FakeGit, override=True)

    # Rebuild the dependency manager
    ctx.dependency_manager = ctx.registry.require("dependency_manager")

    ctx.add_dependency(
        name="baz",
        internal=False,
        optional=False,
        resolver="git",
        method="semver",
        major=3,
        source="gitlab.com/acme/baz.git",
    )


def options(opt):
    opt.load("compiler_cxx")


def configure(conf):
    conf.load("compiler_cxx")


def build(bld):
    bld.program(features="cxx", source="main.cpp", target="app", use=["baz"])
