name: Black
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
  pull_request:
permissions:
  contents: read
jobs:
  Black:
    container:
      image: ghcr.io/steinwurf/black-22:1.0.0
      options: --user 0:0
      volumes:
      - /home/buildbot/.ssh:/root/.ssh
    name: Black 22
    runs-on:
    - self-hosted
    - docker
    - builder
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Black Check
      run: black . --check
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
