name: Flake8
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
  pull_request:
jobs:
  flake8:
    container:
      image: ghcr.io/steinwurf/flake8-4:1.0.0
      options: --user 0:0
      volumes:
      - /home/buildbot/.ssh:/root/.ssh
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    name: Flake8 4.0.1
    runs-on:
    - self-hosted
    - docker
    - builder
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check Python syntax
      run: flake8 . --count --select=E9,F63,F72,F82 --ignore=F632 --show-source --statistics
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
